name: Financial News Agent

on:
  workflow_dispatch:

  schedule:
    - cron: '0 10 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar agente
        env:
  EMAIL: ${{ secrets.EMAIL }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
  DESTINO: ${{ secrets.DESTINO }}
  GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python main.py
